### ISSUE TITLE
Design: UI

### ISSUE THREAD

**Issue by RafaelaDBonis** [Tech-FestivalDoJapao/Gerenciamento#14]
### Descrição

Alterar fluxo da tela de **Recursos**:
* Datas (Dropdown)
* Card de informação de resumos dos recursos (quantidade de voluntários, credenciais, etc)
* Cadastro de ação (total de credenciais e vouchers)
* Mudar senha para o Recurso. Colocar senha automática

**Comment by BiancaFSilva** [comment]
Cadastro de ações, ok

**Comment by BiancaFSilva** [comment]
Auto geração da chave de acesso à área administrativa (tela de recursos) a cada 3 minutos: 
  <img width="40%" src="https://github.com/user-attachments/assets/3d84799d-0082-4555-8cea-42ba80b972d0" />
